use std::path::PathBuf;

pub mod ffi;

/// A structure representing a single file.
///
/// All files in a given directory are pushed to cloud as seperate files. They
/// have an ID associated with them, which is also the name under which
/// they appear in the cloud. This ID is generated by incorporating the local
/// path of the file, its size, and its creation time.
pub struct Node
{
    id: [u8; 32],
    local_path: PathBuf,
}
